[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci --prefix backend --only=production',
  'npm ci --prefix frontend --only=production'
]

[phases.build]
cmds = [
  'cd frontend && npm run build'
]

[start]
cmd = 'node backend/server.js'

[variables]
NODE_ENV = 'production'
